version: '3.8'

volumes:
  db_data:

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: db
  DATABASE_NAME: blackies
  DATABASE_USERNAME: api-user
  DATABASE_PASSWORD: Password1

services:
  app:
    image: template-fluent-mysql:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    ports:
      - '8080:8080'
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

  migrate:
    image: template-fluent-mysql:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0

  revert:
    image: template-fluent-mysql:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: api-user
      MYSQL_PASSWORD: Password1
      MYSQL_DATABASE: blackies
      MYSQL_ROOT_PASSWORD: rootpassword123  # Mejor definir explícitamente la contraseña root
    ports:
      - '3306:3306'

